version: '3.8'

services:
  frontend:
    build:
      context: ./my-react-app
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./spring-boot-app
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_URL=jdbc:mariadb://db:3306/mydatabase
      - DB_USER=myuser
      - DB_PASS=mypassword
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mariadb
    volumes:
      - db_data_prod:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data_prod:
    driver: local
